
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#dsl_support-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#dsl_support-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#dsl_support-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#dsl_support-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#dsl_support-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#dsl_support-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#dsl_support-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#dsl_support-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <img class="tab-pane active" id="dsl_support-ALL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.ALL.gif" />
  <img class="tab-pane " id="dsl_support-CPP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.CPP.gif" />
  <img class="tab-pane " id="dsl_support-OBJC" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.OBJC.gif" />
  <img class="tab-pane " id="dsl_support-JAVA" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.JAVA.gif" />
  <img class="tab-pane " id="dsl_support-HASKELL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.HASKELL.gif" />
  <img class="tab-pane " id="dsl_support-PYTHON" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.PYTHON.gif" />
  <img class="tab-pane " id="dsl_support-RUBY" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.RUBY.gif" />
  <img class="tab-pane " id="dsl_support-LISP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.LISP.gif" />
</div>