
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#dsl_support-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#dsl_support-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#dsl_support-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#dsl_support-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#dsl_support-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#dsl_support-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#dsl_support-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#dsl_support-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <a class="tab-pane active" id="dsl_support-ALL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.ALL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.ALL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-CPP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.CPP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.CPP.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-OBJC" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.OBJC.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.OBJC.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-JAVA" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.JAVA.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.JAVA.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-HASKELL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.HASKELL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.HASKELL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-PYTHON" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.PYTHON.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.PYTHON.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-RUBY" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.RUBY.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.RUBY.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="dsl_support-LISP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.LISP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/dsl_support.LISP.gif" style="max-width: 100%;" />
  </a>
</div>