
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#resource_management-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#resource_management-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#resource_management-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#resource_management-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#resource_management-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#resource_management-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#resource_management-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#resource_management-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <a class="tab-pane active" id="resource_management-ALL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.ALL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.ALL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-CPP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.CPP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.CPP.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-OBJC" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.OBJC.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.OBJC.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-JAVA" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.JAVA.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.JAVA.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-HASKELL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.HASKELL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.HASKELL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-PYTHON" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.PYTHON.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.PYTHON.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-RUBY" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.RUBY.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.RUBY.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="resource_management-LISP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.LISP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.LISP.gif" style="max-width: 100%;" />
  </a>
</div>