
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#resource_management-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#resource_management-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#resource_management-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#resource_management-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#resource_management-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#resource_management-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#resource_management-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#resource_management-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <img class="tab-pane active" id="resource_management-ALL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.ALL.gif" />
  <img class="tab-pane " id="resource_management-CPP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.CPP.gif" />
  <img class="tab-pane " id="resource_management-OBJC" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.OBJC.gif" />
  <img class="tab-pane " id="resource_management-JAVA" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.JAVA.gif" />
  <img class="tab-pane " id="resource_management-HASKELL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.HASKELL.gif" />
  <img class="tab-pane " id="resource_management-PYTHON" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.PYTHON.gif" />
  <img class="tab-pane " id="resource_management-RUBY" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.RUBY.gif" />
  <img class="tab-pane " id="resource_management-LISP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/resource_management.LISP.gif" />
</div>