
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#tools-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#tools-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#tools-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#tools-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#tools-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#tools-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#tools-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#tools-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <a class="tab-pane active" id="tools-ALL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.ALL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.ALL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-CPP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.CPP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.CPP.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-OBJC" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.OBJC.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.OBJC.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-JAVA" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.JAVA.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.JAVA.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-HASKELL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.HASKELL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.HASKELL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-PYTHON" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.PYTHON.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.PYTHON.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-RUBY" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.RUBY.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.RUBY.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="tools-LISP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.LISP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.LISP.gif" style="max-width: 100%;" />
  </a>
</div>