
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#tools-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#tools-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#tools-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#tools-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#tools-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#tools-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#tools-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#tools-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <img class="tab-pane active" id="tools-ALL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.ALL.gif" />
  <img class="tab-pane " id="tools-CPP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.CPP.gif" />
  <img class="tab-pane " id="tools-OBJC" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.OBJC.gif" />
  <img class="tab-pane " id="tools-JAVA" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.JAVA.gif" />
  <img class="tab-pane " id="tools-HASKELL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.HASKELL.gif" />
  <img class="tab-pane " id="tools-PYTHON" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.PYTHON.gif" />
  <img class="tab-pane " id="tools-RUBY" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.RUBY.gif" />
  <img class="tab-pane " id="tools-LISP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/tools.LISP.gif" />
</div>