
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#type_system-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#type_system-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#type_system-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#type_system-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#type_system-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#type_system-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#type_system-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#type_system-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <a class="tab-pane active" id="type_system-ALL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.ALL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.ALL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-CPP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.CPP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.CPP.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-OBJC" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.OBJC.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.OBJC.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-JAVA" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.JAVA.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.JAVA.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-HASKELL" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.HASKELL.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.HASKELL.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-PYTHON" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.PYTHON.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.PYTHON.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-RUBY" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.RUBY.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.RUBY.gif" style="max-width: 100%;" />
  </a>
  <a class="tab-pane " id="type_system-LISP" href="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.LISP.gif">
    <img src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.LISP.gif" style="max-width: 100%;" />
  </a>
</div>