
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#type_system-ALL" class="tab-header tab-header-ALL" data-toggle="tab">All</a>
  </li>
  <li class="">
    <a href="#type_system-CPP" class="tab-header tab-header-CPP" data-toggle="tab">C++</a>
  </li>
  <li class="">
    <a href="#type_system-OBJC" class="tab-header tab-header-OBJC" data-toggle="tab">Objective-C</a>
  </li>
  <li class="">
    <a href="#type_system-JAVA" class="tab-header tab-header-JAVA" data-toggle="tab">Java</a>
  </li>
  <li class="">
    <a href="#type_system-HASKELL" class="tab-header tab-header-HASKELL" data-toggle="tab">Haskell</a>
  </li>
  <li class="">
    <a href="#type_system-PYTHON" class="tab-header tab-header-PYTHON" data-toggle="tab">Python</a>
  </li>
  <li class="">
    <a href="#type_system-RUBY" class="tab-header tab-header-RUBY" data-toggle="tab">Ruby</a>
  </li>
  <li class="">
    <a href="#type_system-LISP" class="tab-header tab-header-LISP" data-toggle="tab">Lisp</a>
  </li>
</ul>
<div class="tab-content">
  <img class="tab-pane active" id="type_system-ALL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.ALL.gif" />
  <img class="tab-pane " id="type_system-CPP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.CPP.gif" />
  <img class="tab-pane " id="type_system-OBJC" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.OBJC.gif" />
  <img class="tab-pane " id="type_system-JAVA" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.JAVA.gif" />
  <img class="tab-pane " id="type_system-HASKELL" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.HASKELL.gif" />
  <img class="tab-pane " id="type_system-PYTHON" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.PYTHON.gif" />
  <img class="tab-pane " id="type_system-RUBY" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.RUBY.gif" />
  <img class="tab-pane " id="type_system-LISP" src="/assets/2013/2013-02-20-visual-guide-to-programming-language-properties/type_system.LISP.gif" />
</div>